/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package approject;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Bunny
 */
public class ViewCourses extends javax.swing.JFrame {

    /**
     * Creates new form ViewCourses
     */
    static String id;
    Connection con=null;
ResultSet rs=null;
PreparedStatement pst=null;
Connection con1=null;
ResultSet rs1=null;
    public ViewCourses(String s) {
        id=s;
        initComponents();
        con= Connect.ConnectDB();
        con1= Connect.ConnectDB();
        Get_Data();
        setLocationRelativeTo(null);
        Get_Data1();
        setLocationRelativeTo(null);
    }
    
   private void Get_Data(){
     String sql="select Name as 'Name1',Code as 'Code', Credits as 'Credits', ME as 'ManDatory/Elective',Instructor as 'Instructor',Acronym as 'Acronym' from courses";
     try{
         pst=con.prepareStatement(sql);
          rs= pst.executeQuery();
         jTable2.setModel(DbUtils.resultSetToTableModel(rs));
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
          
        }
    }
   private void Get_Data1(){
       
     String sql="select * from studentcourses where id='"+id+"'";
     String c1,c2,c3,c4,c5,c6,c7;
     try{
         Statement s = con.createStatement();
      s.executeQuery (sql);
      rs = s.getResultSet ();
      ArrayList<String> db=new ArrayList<String>();
      while (rs.next ())
      {
    	  c1 = rs.getString ("Course1");
          c2 = rs.getString ("Course2");
          c3 = rs.getString ("Course3");
          c4 = rs.getString ("Course4");
          c5 = rs.getString ("Course5");
          c6 = rs.getString ("Course6");
          c7 = rs.getString ("Course7");
          if(c1!=null)
              db.add(c1);
          if(c2!=null)
              db.add(c2);
          if(c3!=null)
              db.add(c3);
          if(c4!=null)
              db.add(c4);
          if(c5!=null)
              db.add(c5);
          if(c6!=null)
              db.add(c6);
          if(c7!=null)
              db.add(c7);
          System.out.println(c1+c2+c3+c4+c5+c6+c7);
      }
      Iterator itr = db.iterator();
      String sqll="select * from courses where ";
      while(itr.hasNext()) {
         Object element = itr.next();
         String ad;
         if(itr.hasNext())
             ad=  "Acronym='"+element.toString()+"' or ";
         else
             ad=  "Acronym='"+element.toString()+"' ";
         sqll=sqll+ad;
      }
      System.out.println(sqll);
      Statement s1 = con1.createStatement();
      s1.executeQuery (sqll);
      rs1 = s1.getResultSet ();
         jTable1.setModel(DbUtils.resultSetToTableModel(rs1));
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
          
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("                                             Registered Courses");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"AP", "Mandatory", "4", "IP", "Programming"},
                {"ELD", "Mandatory", "4", "NONE", "FPGA Arch."},
                {"CTD", "Mandatory", "4", "DC,BE", "N/A"},
                {"SNS", "Mandatory", "4", "NONE", "Signals and Systems"},
                {"Psychology", "Elective", "4", "NONE", "Human Psychology"}
            },
            new String [] {
                "Course Name", "Elective/Mandatory", "Credits", "Pre-Requisite", "Post Conditions"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("                                              Available Courses");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(4).setResizable(false);
            jTable2.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCourses(id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
